### PR TITLE
Remove use of dependency expressions for better bundling

### PR DESCRIPTION
**Pull request by cpvdeveloper**
Fixes https://github.com/omise/omise-node/issues/140
Copy of https://github.com/omise/omise-node/pull/141

### CODE REVIEW

**Comment by danfowler** [comment]
@cpvdeveloper can you resolve conflicts?

**Comment by danfowler** [comment]
@Uponn Thanks. What I mean is: can you resolve the conflicts in your branch?

**Comment by steliyannedev** [comment]
@danfowler I'm not the owner of this PR I just tested the fix locally but if needed I could push the fix.

**Comment by aashishgurung** [comment]
Fixed by [#190](https://github.com/omise/omise-node/pull/190).

**Pull request closed without merging**
